apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Service
metadata:
  name: go-ping-service
  namespace: apps
spec:
  selector: {}
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: go-ping-service-preview
  namespace: apps
spec:
  selector: {}
  ports:
    - name: http
      port: 80
      targetPort: 3000