# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vault
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: default
#   sources:
#   - repoURL: https://helm.releases.hashicorp.com
#     chart: vault
#     targetRevision: 0.30.0
#     helm:
#       releaseName: "vault"
#       valueFiles:
#       - $values/gitops/apps/vault/values.yaml
#   - repoURL: https://github.com/vovsike/DO.git
#     targetRevision: HEAD
#     ref: values

#   destination:
#     namespace: vault
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     - ServerSideApply=true
#     automated:
#       prune: true
#       selfHeal: true