apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-webapp
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: simple-webapp
          image: ghcr.io/vovsike/simple-web-app:v2
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: apiURL
              value: http://go-ping-service:80/