apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-webapp
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: simple-webapp
          image: ghcr.io/vovsike/simple-web-app:v1