apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-ping-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myregistry/myapp:v1   # initial version
          ports:
            - name: http
              containerPort: 8080
  strategy:
    blueGreen:
      activeService: myapp
      autoPromotionEnabled: false   # require manual promotion