apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: eg
      sectionName: http
  hostnames:
    - "vovsike.co.uk"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https