apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vault-op
  name: vault-op
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: vault-op
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata: 
  name: static-auth
  namespace: vault-op
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault_operator_super_admin
    serviceAccount: vault-op
    audiences:
      - vault
      - "system:konnectivity-server"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:authenticated
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: vault-op
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-op
  namespace: vault-op
  annotations:
    kubernetes.io/service-account.name: vault-op
type: kubernetes.io/service-account-token
