apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vault-op
  name: vault-op
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-op
  namespace: vault-op
  annotations:
    kubernetes.io/service-account.name: vault-op
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: vault-op