apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  namespace: apps
spec:
  selector:
      app: simple-webapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-preview
  namespace: apps
spec:
  selector: 
      app: simple-webapp
  ports:
    - name: http
      port: 80
      targetPort: 8080